### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Ingvarr71** [StatiXOS/android_manifest#1]
Hello! When assembling the firmware, I get an error:

FAILED: /home/iodine71/statix/out/soong/build.ninja
/home/iodine71/statix/out/soong/.bootstrap/bin/soong_build -t -l /home/iodine71/statix/out/.module_paths/Android.bp.list -b /home/iodine71/statix/out/soong -n /home/iodine71/statix/out -d /home/iodine71/statix/out/soong/build.ninja.d -globFile /home/iodine71/statix/out/soong/.bootstrap/build-globs.ninja -o /home/iodine71/statix/out/soong/build.ninja Android.bp
internal error: failed to find dex jar path for module "qcom.fmradio"
internal error: failed to find dex jar path for module "qcom.fmradio"
22:37:45 soong bootstrap failed with: exit status 1

How to fix it?

**Comment by itz63c** [comment]
Hey, if you could not open issues on our GitHub in this manner, It would be appreciated. This issue has nothing to do with our source code.
